name: CI
on: push
env:
  CARGO_TERM_COLOR: always

concurrency:
  group: ${{ github.workflow }}-${{ github.ref_name }}
  cancel-in-progress: true

jobs:
  linting:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: webfactory/ssh-agent@v0.6.0
        with:
          ssh-private-key: |
            ${{ secrets.MAMORU_CORE_KEY }}

      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          override: true

      - uses: Swatinem/rust-cache@v2
      - name: Run linting
        run: |
            cargo fmt -- --check
            cargo clippy --workspace --tests -- -D warnings -A clippy::non_canonical_clone_impl -A clippy::redundant_closure_call -A clippy::transmute-int-to-bool
            

  build:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3
      - uses: webfactory/ssh-agent@v0.6.0
        with:
          ssh-private-key: |
            ${{ secrets.MAMORU_CORE_KEY }}

      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          override: true
      - name: Build
        run: cargo build --verbose

  tests:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3
      - uses: webfactory/ssh-agent@v0.6.0
        with:
          ssh-private-key: |
            ${{ secrets.MAMORU_CORE_KEY }}

      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          override: true
      - name: Run tests
        run: make test


  test-coverage:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3
      - uses: webfactory/ssh-agent@v0.6.0
        with:
          ssh-private-key: |
            ${{ secrets.MAMORU_CORE_KEY }}

      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          override: true
      - name: Install cargo-llvm-cov
        run: rustup update && cargo clean && cargo install cargo-llvm-cov --quiet
      - name: Generate code coverage
        run: cargo llvm-cov

