name: "Release Cross"
on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'The release tag. Must follow Rust versioning conventions, e.g. "0.0.0"'
        required: true

env:
  CRATE_NAME: mamorurs-cli
  GITHUB_TOKEN: ${{ github.token }}
  RUST_BACKTRACE: 1
  CARGO_NET_GIT_FETCH_WITH_CLI: true

permissions:
  contents: write

jobs:
  build:
    name: Release - ${{ matrix.platform.release_for }}
    strategy:
      matrix:
        platform:
          - release_for: Linux-x86_64
            os: ubuntu-20.04
            target: x86_64-unknown-linux-gnu
            bin: mamorurs-cli
            name: mamorurs-cli-linux-x86_64.zip


          - release_for: macOS-x86_64
            os: macos-latest
            target: x86_64-apple-darwin
            bin: mamorurs-cli
            name: mamorurs-cli-darwin-x86_64.zip

          - release_for: macOS-aarch64
            os: macOS-latest
            target: aarch64-apple-darwin
            bin: mamorurs-cli
            name: mamorurs-cli-darwin-aarch64.zip


    runs-on: ${{ matrix.platform.os }}
    steps:

      - name: Checkout source code
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: |
            ${{ secrets.MAMORU_CORE_KEY }}
            ${{ secrets.VALIDATION_CHAIN_KEY }}

      - uses: arduino/setup-protoc@v3
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          version: "23.x"

      - uses: Swatinem/rust-cache@v2

      - name: Build binary
        uses: houseabsolute/actions-rust-cross@v0
        with:
          command: "build"
          target: ${{ matrix.platform.target }}
          args: "--locked --release"
          strip: true

      - name: Upload release binaries
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.platform.name }}
          path: | 
            ./target/${{ matrix.platform.target }}/release/${{ matrix.platform.bin }}


  release:
    name: Release Binaries
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          path: ./release-binaries/

      - name: Display matching files for release
        run: |
          echo "Matching files:"
          ls -lh ./release-binaries/*.zip

      - name: release
        uses: softprops/action-gh-release@v2
        with:
          files: "release-binaries/*.zip"
          draft: false
          prerelease: false
          tag_name: ${{ github.event.inputs.tag }}
          body: "Release ${{ github.event.inputs.tag }}"
          token: ${{ secrets.GITHUB_TOKEN }}
          generate_release_notes: true
